# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c0a1c26cebdf0a22fcd2ef364795ed0c676ece01386b56e8dbf5e391c31b7f4826864dd63824241f205ae11b82bf11ce40d65c398555b219642eef0feb1a60c

test:
  secret_key_base: de1d1cc8151d31f3e9067396acee1c3bf77f7acc9573bcc13baf02fe437447e6522a648dddd8589c0ae564d6a1314329ef279b07037a1957b4757fd3069b2485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
